services:
  python-docker-service-template:
    build:
      context: .
      dockerfile: Dockerfile
    image: python-docker-service-template:local
    restart: unless-stopped
    init: true
    mem_limit: 1g
    environment:
      PYTHONUNBUFFERED: "1"
