services:
  python-docker-service-template:
    build:
      context: .
      dockerfile: Dockerfile
    image: python-docker-service-template:local
    container_name: python-docker-service-template
    restart: unless-stopped
    init: true
    environment:
      PYTHONUNBUFFERED: "1"
